import assert from 'node:assert/strict';
import test from 'node:test';
import { GetObjectCommand, PutObjectCommand, DeleteObjectCommand, type S3Client } from '@aws-sdk/client-s3';
import { S3ObjectStore, requireS3Configuration, departmentPatchPathFromMetadata } from './s3-object-store-core.ts';
import type { AttachmentObjectPath, DepartmentAssetObjectPath } from './object-store-core.ts';
const department='10000000-0000-4000-8000-000000000001', foreign='20000000-0000-4000-8000-000000000002';
const base={departmentId:department,recordId:'30000000-0000-4000-8000-000000000003',objectId:'40000000-0000-4000-8000-000000000004',fileName:'test.pdf',bytes:new Uint8Array([1,2,3]),contentType:'application/pdf'};
function fixture(fail=false){const calls:Array<PutObjectCommand|DeleteObjectCommand|GetObjectCommand>=[];const client={send:async(command:PutObjectCommand|DeleteObjectCommand)=>{calls.push(command);if(fail)throw new Error('secret error contents');return {};}} as unknown as S3Client;const store=new S3ObjectStore(client,'tracepoint-staging-private-559054714699','559054714699',department,async(_client,command,options)=>{calls.push(command as unknown as GetObjectCommand);assert.equal(options?.expiresIn,60);if(fail)throw new Error('secret');return 'https://private.invalid/signed';});return {store,calls};}
test('S3 uploads every attachment domain privately with owner and immutable write checks',async()=>{const {store,calls}=fixture();for(const method of ['uploadQualificationEvidence','uploadTrainingFile','uploadFirearmAttachment','uploadDrillDocument'] as const){const result=await store[method](base);assert.equal(result.error,null);assert.ok(result.path.startsWith(department+'/'));}for(const command of calls){assert.ok(command instanceof PutObjectCommand);assert.equal(command.input.ExpectedBucketOwner,'559054714699');assert.equal(command.input.ServerSideEncryption,'AES256');assert.equal(command.input.IfNoneMatch,'*');assert.equal(command.input.ACL,undefined);assert.ok(command.input.Key?.startsWith('attachments/'+department+'/'));}});
test('S3 download, view and delete use validated keys and short-lived delivery',async()=>{const {store,calls}=fixture();const upload=await store.uploadDrillDocument(base);assert.equal((await store.createAttachmentDownload(upload.path,'a"\r\nname.pdf')).error,null);assert.equal((await store.createAttachmentView(upload.path)).error,null);assert.equal((await store.removeAttachment(upload.path)).error,null);assert.ok(calls[1] instanceof GetObjectCommand);assert.doesNotMatch(calls[1].input.ResponseContentDisposition??'',/[\r\n]/);assert.ok(calls[3] instanceof DeleteObjectCommand);});
test('S3 rejects cross-tenant uploads and forged metadata before SDK access',async()=>{const {store,calls}=fixture();await assert.rejects(store.uploadDrillDocument({...base,departmentId:foreign}));for(const key of [foreign+'/drill-document/a/b',department+'/drill-document/../b',department+'/drill-document/%25252e%25252e/b',department+'/drill-document/%2525252e%2525252e/b',department+'/drill-document/a/%00',department+'/drill-document/a\\b/c',department+'/drill-document/a/%zz']){await assert.rejects(async()=>store.createAttachmentView(key as AttachmentObjectPath));await assert.rejects(async()=>store.removeAttachment(key as AttachmentObjectPath));}assert.equal(calls.length,0);});
test('S3 rejects unsafe upload record and object identifiers',async()=>{const {store,calls}=fixture();for(const value of ['..','../other','%25252e%25252e','a/b'])await assert.rejects(store.uploadDrillDocument({...base,recordId:value}));await assert.rejects(store.uploadTrainingFile({...base,objectId:'../bad'}));assert.equal(calls.length,0);});
test('department patch delivery remains a stable authenticated path and view is signed',async()=>{const {store,calls}=fixture();const result=await store.uploadDepartmentPatch({departmentId:department,extension:'png',bytes:base.bytes,contentType:'image/png',timestamp:123});const delivery=await store.createDepartmentPatchDelivery(result.path);assert.equal(delivery.signedUrl,'/api/settings/department-patch?path='+encodeURIComponent(result.path));assert.equal(calls.length,1);assert.equal((await store.createDepartmentPatchView(result.path)).error,null);assert.equal((await store.removeDepartmentPatch(result.path)).error,null);assert.equal(departmentPatchPathFromMetadata(foreign+'/patch-123.png',department),null);await assert.rejects(async()=>store.createDepartmentPatchView((department+'/../patch-1.png') as DepartmentAssetObjectPath));});
test('storage errors are sanitized without retrying ambiguous writes',async()=>{const {store,calls}=fixture(true);const result=await store.uploadDrillDocument(base);assert.equal(result.error?.message,'Object storage operation failed.');assert.equal(calls.length,1);assert.equal((await store.createAttachmentView(result.path)).signedUrl,null);});
test('configuration isolates account, environment, bucket and region',()=>{const env={CONFIGURATION_ENVIRONMENT:'staging',AWS_REGION:'us-east-1',TRACEPOINT_S3_EXPECTED_OWNER:'559054714699',TRACEPOINT_S3_BUCKET:'tracepoint-staging-private-559054714699'};assert.equal(requireS3Configuration(env).account,'559054714699');for(const override of [{CONFIGURATION_ENVIRONMENT:'production'},{AWS_REGION:'us-west-2'},{TRACEPOINT_S3_EXPECTED_OWNER:'265544358665'},{TRACEPOINT_S3_BUCKET:'public-bucket'}])assert.throws(()=>requireS3Configuration({...env,...override}));assert.equal(requireS3Configuration({...env,CONFIGURATION_ENVIRONMENT:'production',TRACEPOINT_S3_EXPECTED_OWNER:'111111111111',TRACEPOINT_S3_BUCKET:'tracepoint-production-private-111111111111'}).account,'111111111111');});
