export const COURSE_CATALOG_FIELDS = "id,canonical_title,training_type,category,description,topics,default_location,default_hours,lesson_plan_required,certification_type_id,certification_valid_days,certificate_enabled,certificate_title,usage_count,last_used_at,is_active,agency_training_course_aliases(id,alias_title)";
export type CourseCatalogRow = Record<string, unknown> & { agency_training_course_aliases?: Array<{ alias_title: string }> | null };
type QueryResult = { data: CourseCatalogRow[] | null; error: { message: string } | null };
type TitleOrder = { order(column: string, options: { ascending: boolean }): PromiseLike<QueryResult> };
type UsageOrder = { order(column: string, options: { ascending: boolean }): TitleOrder };
type ActiveFilter = { eq(column: string, value: boolean): UsageOrder };
type DepartmentFilter = { eq(column: string, value: string): ActiveFilter };
export type CourseCatalogSupabaseClient = { from(table: "agency_training_courses"): { select(fields: string): DepartmentFilter } };
export interface CourseCatalogRepository { listActiveCourses(input: { departmentId: string }): Promise<CourseCatalogRow[]>; }
export class CourseCatalogAuthorizationError extends Error { constructor() { super("Authorized department context is required."); this.name = "CourseCatalogAuthorizationError"; } }
export class CourseCatalogRepositoryError extends Error { constructor() { super("Training courses could not be loaded."); this.name = "CourseCatalogRepositoryError"; } }
export class CourseCatalogRepositoryConfigurationError extends Error { constructor(provider: string) { super(`Unsupported data provider: ${provider}. Only supabase is implemented.`); this.name = "CourseCatalogRepositoryConfigurationError"; } }
export class SupabaseCourseCatalogRepository implements CourseCatalogRepository { private readonly client: CourseCatalogSupabaseClient; private readonly authorizedDepartmentId: string; constructor(client: CourseCatalogSupabaseClient, authorizedDepartmentId: string) { if (!authorizedDepartmentId) throw new CourseCatalogAuthorizationError(); this.client = client; this.authorizedDepartmentId = authorizedDepartmentId; } async listActiveCourses(input: { departmentId: string }) { if (!input.departmentId || input.departmentId !== this.authorizedDepartmentId) throw new CourseCatalogAuthorizationError(); const result = await this.client.from("agency_training_courses").select(COURSE_CATALOG_FIELDS).eq("department_id", input.departmentId).eq("is_active", true).order("usage_count", { ascending: false }).order("canonical_title", { ascending: true }); if (result.error) throw new CourseCatalogRepositoryError(); return result.data ?? []; } }
export function mapCourseCatalogRow(row: CourseCatalogRow) { const aliases = Array.isArray(row.agency_training_course_aliases) ? row.agency_training_course_aliases : []; return { id: row.id, canonicalTitle: row.canonical_title, aliases: aliases.map((alias) => alias.alias_title), trainingType: row.training_type, category: row.category, description: row.description, topics: row.topics ?? [], defaultLocation: row.default_location, defaultHours: row.default_hours, lessonPlanRequired: row.lesson_plan_required, certificationTypeId: row.certification_type_id, certificationValidDays: row.certification_valid_days, certificateEnabled: row.certificate_enabled, certificateTitle: row.certificate_title, usageCount: row.usage_count, lastUsedAt: row.last_used_at, isActive: row.is_active }; }
export function createCourseCatalogRepository(client: CourseCatalogSupabaseClient, departmentId: string, environment?: { TRACEPOINT_DATA_PROVIDER?: string }) { const provider = (environment ? environment.TRACEPOINT_DATA_PROVIDER : process.env.TRACEPOINT_DATA_PROVIDER)?.trim().toLowerCase() || "supabase"; if (provider !== "supabase") throw new CourseCatalogRepositoryConfigurationError(provider); return new SupabaseCourseCatalogRepository(client, departmentId); }
