import assert from "node:assert/strict";
import test from "node:test";
import { createCurrentRulesRepository, CURRENT_RULES_FIELDS, CurrentRulesAuthorizationError, CurrentRulesRepositoryConfigurationError, CurrentRulesRepositoryError, mapCurrentRules, SupabaseCurrentRulesRepository, type CurrentRulesRow, type CurrentRulesSupabaseClient } from "./current-rules-repository-core.ts";

function client(result: { data: CurrentRulesRow | null; error: { message: string } | null }, calls: string[]): CurrentRulesSupabaseClient { return { from(table) { calls.push(`from:${table}`); return { select(fields) { calls.push(`select:${fields}`); return { eq(column, value) { calls.push(`eq:${column}:${value}`); return { maybeSingle() { calls.push("maybeSingle"); return Promise.resolve(result); } }; } }; } }; } }; }

test("preserves the exact tenant-bound read-only query", async () => { const calls: string[] = []; const repository = new SupabaseCurrentRulesRepository(client({ data: null, error: null }, calls), "department-a"); assert.equal(await repository.getCurrentRules({ departmentId: "department-a" }), null); assert.deepEqual(calls, [`from:department_rules`, `select:${CURRENT_RULES_FIELDS}`, "eq:department_id:department-a", "maybeSingle"]); assert.equal("insert" in repository || "update" in repository || "delete" in repository, false); });
test("preserves defaults, nulls, and numeric coercion", () => { assert.deepEqual(mapCurrentRules(null), { spring_cycle_start: "04-01", spring_cycle_end: "06-30", fall_cycle_start: "09-01", fall_cycle_end: "11-30", qualification_valid_days: 365, qualification_due_soon_days: 30, inspection_interval_days: 180, battery_check_interval_days: 180, off_duty_renewal_days: 365 }); assert.equal(mapCurrentRules({ spring_cycle_start: null, spring_cycle_end: null, fall_cycle_start: null, fall_cycle_end: null, qualification_valid_days: "400", qualification_due_soon_days: "0", inspection_interval_days: "90", battery_check_interval_days: "0", off_duty_renewal_days: "700" }).qualification_due_soon_days, 0); });
test("rejects missing and cross-department context before querying", async () => { const calls: string[] = []; assert.throws(() => new SupabaseCurrentRulesRepository(client({ data: null, error: null }, calls), ""), CurrentRulesAuthorizationError); const repository = new SupabaseCurrentRulesRepository(client({ data: null, error: null }, calls), "department-a"); await assert.rejects(repository.getCurrentRules({ departmentId: "department-b" }), CurrentRulesAuthorizationError); assert.deepEqual(calls, []); });
test("maps provider failure and rejects unsupported providers", async () => { const repository = new SupabaseCurrentRulesRepository(client({ data: null, error: { message: "synthetic internal detail" } }, []), "department-a"); await assert.rejects(repository.getCurrentRules({ departmentId: "department-a" }), (error) => error instanceof CurrentRulesRepositoryError && !error.message.includes("internal")); assert.throws(() => createCurrentRulesRepository(client({ data: null, error: null }, []), "department-a", { TRACEPOINT_DATA_PROVIDER: "aurora" }), CurrentRulesRepositoryConfigurationError); });
