export const CURRENT_RULES_FIELDS = "spring_cycle_start,spring_cycle_end,fall_cycle_start,fall_cycle_end,qualification_valid_days,qualification_due_soon_days,inspection_interval_days,battery_check_interval_days,off_duty_renewal_days";

export type CurrentRulesRow = { spring_cycle_start: string | null; spring_cycle_end: string | null; fall_cycle_start: string | null; fall_cycle_end: string | null; qualification_valid_days: number | string | null; qualification_due_soon_days: number | string | null; inspection_interval_days: number | string | null; battery_check_interval_days: number | string | null; off_duty_renewal_days: number | string | null };
type QueryResult = { data: CurrentRulesRow | null; error: { message: string } | null };
export type CurrentRulesSupabaseClient = { from(table: "department_rules"): { select(fields: string): { eq(column: string, value: string): { maybeSingle(): PromiseLike<QueryResult> } } } };
export interface CurrentRulesRepository { getCurrentRules(input: { departmentId: string }): Promise<CurrentRulesRow | null>; }
export class CurrentRulesAuthorizationError extends Error { constructor() { super("Authorized department context is required."); this.name = "CurrentRulesAuthorizationError"; } }
export class CurrentRulesRepositoryError extends Error { constructor() { super("Department rules could not be loaded."); this.name = "CurrentRulesRepositoryError"; } }
export class CurrentRulesRepositoryConfigurationError extends Error { constructor(provider: string) { super(`Unsupported data provider: ${provider}. Only supabase is implemented.`); this.name = "CurrentRulesRepositoryConfigurationError"; } }
export class SupabaseCurrentRulesRepository implements CurrentRulesRepository {
  private readonly client: CurrentRulesSupabaseClient;
  private readonly authorizedDepartmentId: string;
  constructor(client: CurrentRulesSupabaseClient, authorizedDepartmentId: string) { if (!authorizedDepartmentId) throw new CurrentRulesAuthorizationError(); this.client = client; this.authorizedDepartmentId = authorizedDepartmentId; }
  async getCurrentRules(input: { departmentId: string }) { if (!input.departmentId || input.departmentId !== this.authorizedDepartmentId) throw new CurrentRulesAuthorizationError(); const result = await this.client.from("department_rules").select(CURRENT_RULES_FIELDS).eq("department_id", input.departmentId).maybeSingle(); if (result.error) throw new CurrentRulesRepositoryError(); return result.data; }
}
export function mapCurrentRules(row: CurrentRulesRow | null) { return { spring_cycle_start: row?.spring_cycle_start ?? "04-01", spring_cycle_end: row?.spring_cycle_end ?? "06-30", fall_cycle_start: row?.fall_cycle_start ?? "09-01", fall_cycle_end: row?.fall_cycle_end ?? "11-30", qualification_valid_days: Number(row?.qualification_valid_days) || 365, qualification_due_soon_days: row?.qualification_due_soon_days == null ? 30 : Number(row.qualification_due_soon_days), inspection_interval_days: Number(row?.inspection_interval_days) || 180, battery_check_interval_days: Number(row?.battery_check_interval_days) || 180, off_duty_renewal_days: Number(row?.off_duty_renewal_days) || 365 }; }
export function createCurrentRulesRepository(client: CurrentRulesSupabaseClient, departmentId: string, environment?: { TRACEPOINT_DATA_PROVIDER?: string }) { const provider = (environment ? environment.TRACEPOINT_DATA_PROVIDER : process.env.TRACEPOINT_DATA_PROVIDER)?.trim().toLowerCase() || "supabase"; if (provider !== "supabase") throw new CurrentRulesRepositoryConfigurationError(provider); return new SupabaseCurrentRulesRepository(client, departmentId); }
