"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { AlertTriangle, ArrowLeft, Car, ClipboardCheck, FileText, History, Plus, RefreshCw, Settings2, Wrench } from "lucide-react";
import TracePointShell from "@/app/components/TracePointShell";
import QuickInspectionPanel from "./QuickInspectionPanel";
import FleetWorkOrderDialog from "./FleetWorkOrderDialog";
import FleetEquipmentDialog from "./FleetEquipmentDialog";

type Tab = "overview" | "inspections" | "maintenance" | "equipment" | "documents" | "history";
type Payload = { vehicle: any; inspections: any[]; workOrders: any[]; equipment: any[]; documents: any[]; history: any[]; rules: any; canManage: boolean; canMaintain: boolean; canConfigure: boolean; canViewNetworkDetails: boolean };

const PREVIEW: Payload = {
  vehicle: { id: "preview", unit_number: "3101", vin: "1FM5K8AR0NGA00001", license_plate: "MG-3101", year: 2025, make: "Ford", model: "Police Interceptor Utility", vehicle_type: "Patrol", assignment_type: "Pool", assigned_to: "Patrol Division", home_location: "Headquarters", current_mileage: 18422, current_hours: 2167.4, status: "Attention", status_override_active: false, inspection_due_date: "2026-09-12", registration_expiration_date: "2027-01-31", next_service_date: "2026-09-05", next_service_mileage: 20000, next_service_hours: 2300 },
  workOrders: [{ id: "preview-work", record_type: "Issue", title: "Driver-side spotlight intermittent", description: "Light flickers when the vehicle is idling.", priority: "High", status: "Assigned", assigned_role_code: "mechanic", reported_at: "2026-08-24T14:00:00Z", total_cost: null }],
  inspections: [{ id: "preview-inspection", inspection_type: "Pre-Shift", result: "Passed", mileage: 18395, hours: 2164.2, defect_count: 0, inspected_at: "2026-08-24T11:45:00Z", checklist: [] }],
  equipment: [
    { id: "preview-mdt", category: "MDT", name: "Patrol MDT", make: "Panasonic", model: "Toughbook 55", year: 2025, serial_number: "MDT-3101-25", warranty_expiration_date: "2028-05-01", source_type: "Linked Inventory", status: "Current", is_required: true, is_critical: false },
    { id: "preview-modem", category: "Modem", name: "Vehicle Modem", make: "Cradlepoint", model: "R1900", year: 2025, serial_number: "MODEM-3101", warranty_expiration_date: "2028-05-01", static_ip: "10.10.31.1", source_type: "Fleet Checklist", status: "Current", is_required: true, is_critical: true },
    { id: "preview-radar", category: "Radar", name: "Mobile Radar", make: "Stalker", model: "DSR 2X", year: 2025, serial_number: "RADAR-3101", tuning_fork_serial_number: "TF-3101-A", warranty_expiration_date: "2027-05-01", source_type: "Fleet Checklist", status: "Current", is_required: false, is_critical: false },
  ],
  documents: [{ id: "preview-doc", title: "Vehicle Registration", document_type: "Registration", expiration_date: "2027-01-31", document_url: null }],
  history: [{ id: "preview-history", action: "fleet_vehicle_created", created_at: "2026-08-24T13:00:00Z" }],
  rules: { fleet_manager_role_codes: ["fleet_manager"], mechanic_role_codes: ["mechanic"], inspection_include_required_equipment: true }, canManage: true, canMaintain: true, canConfigure: true, canViewNetworkDetails: true,
};

function formatDate(value?: string | null) { if (!value) return "—"; const date = new Date(value.includes("T") ? value : `${value}T00:00:00`); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
function money(value: unknown) { const number = Number(value); return Number.isFinite(number) && number > 0 ? number.toLocaleString("en-US", { style: "currency", currency: "USD" }) : "—"; }
function statusClass(status: string) { return status === "Available" || status === "Current" || status === "Completed" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" : status === "Attention" || status === "Open" || status === "High" ? "border-amber-500/30 bg-amber-500/10 text-amber-300" : status === "Out of Service" || status === "Critical" || status === "Missing" ? "border-red-500/30 bg-red-500/10 text-red-300" : status === "Retired" || status === "Cancelled" || status === "Removed" ? "border-slate-700 bg-slate-800 text-slate-400" : "border-blue-500/30 bg-blue-500/10 text-blue-300"; }
async function errorText(response: Response) { const payload = await response.json().catch(() => ({})); return payload.error || "Request failed."; }

export default function VehiclePage() {
  const { vehicleId } = useParams<{ vehicleId: string }>();
  const [data, setData] = useState<Payload | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [workDialog, setWorkDialog] = useState<{ mode: "issue" | "maintenance"; item?: any } | null>(null);
  const [equipmentDialog, setEquipmentDialog] = useState(false);

  const load = useCallback(async () => { setLoading(true); setError(""); try { if (vehicleId === "preview") { setData(PREVIEW); setMessage("Local preview mode — actions are displayed but data changes are disabled until the Fleet migration is applied."); return; } const response = await fetch(`/api/fleet/vehicles/${vehicleId}`, { cache: "no-store" }); if (!response.ok) throw new Error(await errorText(response)); setData(await response.json()); } catch (e) { setError(e instanceof Error ? e.message : "Vehicle could not be loaded."); } finally { setLoading(false); } }, [vehicleId]);
  useEffect(() => { void load(); }, [load]);

  async function request(path: string, method: string, body: any) { if (vehicleId === "preview") { setMessage("Preview only: apply the Fleet migration when you are ready to test saved records."); return; } setSaving(true); setError(""); setMessage(""); try { const response = await fetch(path, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await errorText(response)); setMessage("Saved and recorded in the audit history."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "The change could not be saved."); } finally { setSaving(false); } }
  async function workSaved(savedMessage: string) { setMessage(savedMessage); if (vehicleId !== "preview") await load(); }
  async function addDocument() { const title = window.prompt("Document title"); if (!title) return; const documentType = window.prompt("Document type", "Registration") || "Other"; const expirationDate = window.prompt("Expiration date (YYYY-MM-DD), or leave blank", "") || ""; const documentUrl = window.prompt("Document link, or leave blank", "") || ""; await request(`/api/fleet/vehicles/${vehicleId}/documents`, "POST", { title, documentType, expirationDate, documentUrl }); }
  async function updateStatus(status: string) { const reason = window.prompt(`Reason for changing this vehicle to ${status}`); if (!reason) return; await request(`/api/fleet/vehicles/${vehicleId}`, "PATCH", { status, reason }); }

  const openOrders = useMemo(() => data?.workOrders.filter((item) => !["Completed", "Cancelled"].includes(item.status)) ?? [], [data]);
  if (loading && !data) return <TracePointShell activePage="Fleet Management"><div className="flex h-72 items-center justify-center"><RefreshCw className="animate-spin text-blue-300" /></div></TracePointShell>;
  if (!data) return <TracePointShell activePage="Fleet Management"><div className="rounded-2xl border border-red-700 bg-red-950/30 p-5 text-red-200">{error || "Vehicle was not found."}</div></TracePointShell>;
  const v = data.vehicle;
  const tabs: Array<[Tab,string,number?]> = [["overview","Overview"],["inspections","Inspections",data.inspections.length],["maintenance","Maintenance",openOrders.length],["equipment","Equipment",data.equipment.length],["documents","Documents",data.documents.length],["history","History",data.history.length]];
  return <TracePointShell activePage="Fleet Management"><div className="mx-auto w-full max-w-[1600px] space-y-5">
    <header className="rounded-3xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><Link href="/fleet-management" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-white"><ArrowLeft size={14}/>Fleet Management</Link><div className="mt-4 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-blue-500/20 bg-blue-500/10"><Car className="text-blue-300"/></div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-white">Unit {v.unit_number}</h1><span className={`rounded-full border px-2.5 py-1 text-[9px] font-bold uppercase ${statusClass(v.status)}`}>{v.status}</span></div><p className="mt-1 text-xs text-slate-400">{[v.year,v.make,v.model].filter(Boolean).join(" ") || "Vehicle details pending"} · {v.license_plate || "No plate"}</p></div></div></div><div className="flex flex-wrap gap-2"><button onClick={() => setTab("inspections")} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><ClipboardCheck size={14} className="mr-2 inline"/>Quick Inspect</button><button onClick={() => setWorkDialog({ mode: "issue" })} className="rounded-xl border border-amber-600/50 px-3 py-2 text-xs font-semibold text-amber-200"><AlertTriangle size={14} className="mr-2 inline"/>Report Issue</button>{data.canMaintain ? <button onClick={() => setWorkDialog({ mode: "maintenance" })} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Wrench size={14} className="mr-2 inline"/>Add Maintenance</button> : null}{data.canConfigure ? <Link href="/settings/fleet" className="rounded-xl border border-slate-700 px-3 py-2 text-slate-400 hover:text-white"><Settings2 size={15}/></Link> : null}<button onClick={() => void load()} className="rounded-xl border border-slate-700 px-3 py-2 text-slate-400 hover:text-white"><RefreshCw size={15}/></button></div></div></header>
    {error ? <div className="rounded-xl border border-red-700 bg-red-950/30 p-4 text-sm text-red-200">{error}</div> : null}{message ? <div className="rounded-xl border border-emerald-700 bg-emerald-950/30 p-4 text-sm text-emerald-200">{message}</div> : null}
    <nav className="flex overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/70 p-1">{tabs.map(([id,label,count]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-xs font-semibold ${tab === id ? "bg-slate-800 text-white" : "text-slate-500 hover:text-slate-300"}`}>{label}{count !== undefined ? ` (${count})` : ""}</button>)}</nav>
    {tab === "overview" ? <div className="grid gap-4 xl:grid-cols-3"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 xl:col-span-2"><h2 className="font-bold text-white">Vehicle Overview</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["VIN",v.vin],["License Plate",v.license_plate],["Type",v.vehicle_type],["Assignment",v.assigned_to || v.assignment_type],["Location",v.home_location],["Mileage",`${Number(v.current_mileage||0).toLocaleString()} mi`],["Engine Hours",`${Number(v.current_hours||0).toLocaleString()} hrs`],["Inspection Due",formatDate(v.inspection_due_date)],["Registration Expires",formatDate(v.registration_expiration_date)],["Next Service",formatDate(v.next_service_date)],["Service Mileage",v.next_service_mileage ? `${Number(v.next_service_mileage).toLocaleString()} mi` : "—"],["Service Hours",v.next_service_hours ? `${Number(v.next_service_hours).toLocaleString()} hrs` : "—"]].map(([label,value]) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><p className="text-[9px] font-semibold uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-sm font-semibold text-slate-300">{value || "—"}</p></div>)}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold text-white">Manage Status</h2><p className="mt-2 text-xs leading-5 text-slate-500">Hybrid readiness evaluates open work and critical equipment. Overrides require a reason.</p>{data.canManage ? <div className="mt-4 grid gap-2">{["Available","Attention","Maintenance","Out of Service","Retired"].map((status) => <button key={status} disabled={saving || status === v.status} onClick={() => void updateStatus(status)} className={`rounded-xl border px-3 py-2 text-left text-xs font-semibold disabled:opacity-40 ${statusClass(status)}`}>{status}</button>)}</div> : null}</section></div> : null}
    {tab === "inspections" ? <QuickInspectionPanel vehicleId={vehicleId} vehicle={v} inspections={data.inspections} rules={data.rules} equipment={data.equipment} onSaved={load}/> : null}
    {tab === "maintenance" ? <section className="rounded-2xl border border-slate-800 bg-slate-900/70"><div className="flex items-center justify-between border-b border-slate-800 p-4"><div><h2 className="font-bold text-white">Issues and Maintenance Work Orders</h2><p className="mt-1 text-xs text-slate-500">Officers report issues; mechanics document service, repairs, cost, and completion.</p></div>{data.canMaintain ? <button onClick={() => setWorkDialog({ mode: "maintenance" })} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/>Add Maintenance</button> : null}</div><div className="divide-y divide-slate-800">{data.workOrders.length ? data.workOrders.map((item) => <article key={item.id} className="p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-white">{item.title}</h3>{item.issue_category ? <span className="rounded-full border border-slate-700 px-2 py-1 text-[9px] font-bold uppercase text-slate-400">{item.issue_category}</span> : null}<span className={`rounded-full border px-2 py-1 text-[9px] font-bold uppercase ${statusClass(item.priority)}`}>{item.priority}</span><span className={`rounded-full border px-2 py-1 text-[9px] font-bold uppercase ${statusClass(item.status)}`}>{item.status}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{item.description || "No additional description."}</p><p className="mt-2 text-[10px] text-slate-500">{item.record_type} · Reported {formatDate(item.reported_at)} · Assigned to {item.mechanic_name || item.assigned_role_code || "Unassigned"} · Cost {money(item.total_cost)}</p>{item.resolution ? <p className="mt-2 rounded-lg bg-slate-950/60 p-2 text-xs text-slate-300">Resolution: {item.resolution}</p> : null}</div>{data.canMaintain ? <button onClick={() => setWorkDialog({ mode: "maintenance", item })} className="rounded-xl border border-blue-500/40 px-3 py-2 text-xs font-semibold text-blue-200">Manage Work Order</button> : null}</div></article>) : <div className="p-10 text-center text-sm text-slate-500">No issues or maintenance work recorded.</div>}</div></section> : null}
    {tab === "equipment" ? <section className="rounded-2xl border border-slate-800 bg-slate-900/70"><div className="flex flex-col gap-3 border-b border-slate-800 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-white">Installed and Required Equipment</h2><p className="mt-1 text-xs text-slate-500">Link tracked TracePoint inventory or create a complete Fleet-only equipment record.</p></div>{data.canManage ? <button onClick={() => setEquipmentDialog(true)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/>Add Equipment</button> : null}</div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{data.equipment.length ? data.equipment.map((item) => <article key={item.id} className="rounded-xl border border-slate-800 bg-slate-950/40 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-wider text-blue-400">{item.category}</p><h3 className="mt-1 text-sm font-bold text-white">{item.name}</h3></div><span className={`rounded-full border px-2 py-1 text-[9px] font-bold uppercase ${statusClass(item.status)}`}>{item.status}</span></div><p className="mt-3 text-xs text-slate-400">{[item.year,item.make,item.model].filter(Boolean).join(" ") || "Details pending"}</p><div className="mt-3 space-y-1 text-[10px] text-slate-500"><p>Serial: {item.serial_number || "—"}</p>{item.tuning_fork_serial_number ? <p>Tuning fork: {item.tuning_fork_serial_number}</p> : null}<p>Warranty: {formatDate(item.warranty_expiration_date)}</p>{item.static_ip ? <p>Static IP: {item.static_ip}</p> : null}<p>{item.source_type}{item.is_required ? " · Required" : ""}{item.is_critical ? " · Critical" : ""}</p></div></article>) : <div className="col-span-full p-10 text-center text-sm text-slate-500">No vehicle equipment recorded.</div>}</div></section> : null}
    {tab === "documents" ? <section className="rounded-2xl border border-slate-800 bg-slate-900/70"><div className="flex items-center justify-between border-b border-slate-800 p-4"><h2 className="font-bold text-white">Vehicle Documents</h2>{data.canManage ? <button onClick={() => void addDocument()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/>Add Document</button> : null}</div><div className="divide-y divide-slate-800">{data.documents.length ? data.documents.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 p-4"><div className="flex items-center gap-3"><FileText className="text-blue-300"/><div><p className="text-sm font-semibold text-white">{item.title}</p><p className="mt-1 text-[10px] text-slate-500">{item.document_type} · Expires {formatDate(item.expiration_date)}</p></div></div>{item.document_url ? <a href={item.document_url} target="_blank" rel="noreferrer" className="text-xs font-semibold text-blue-300">Open</a> : null}</div>) : <div className="p-10 text-center text-sm text-slate-500">No documents recorded.</div>}</div></section> : null}
    {tab === "history" ? <section className="rounded-2xl border border-slate-800 bg-slate-900/70"><div className="border-b border-slate-800 p-4"><h2 className="font-bold text-white">Permanent Activity History</h2></div><div className="divide-y divide-slate-800">{data.history.length ? data.history.map((item) => <div key={item.id} className="flex gap-3 p-4"><History size={16} className="mt-0.5 text-blue-300"/><div><p className="text-xs font-semibold text-slate-300">{String(item.action).replaceAll("_"," ")}</p><p className="mt-1 text-[10px] text-slate-500">{formatDate(item.created_at)}</p></div></div>) : <div className="p-10 text-center text-sm text-slate-500">No Fleet history recorded yet.</div>}</div></section> : null}
    {workDialog ? <FleetWorkOrderDialog mode={workDialog.mode} vehicleId={vehicleId} vehicle={v} item={workDialog.item} onClose={() => setWorkDialog(null)} onSaved={workSaved}/> : null}
    {equipmentDialog ? <FleetEquipmentDialog vehicleId={vehicleId} vehicle={v} existingEquipment={data.equipment} onClose={() => setEquipmentDialog(false)} onSaved={workSaved}/> : null}
  </div></TracePointShell>;
}
