import {test} from 'node:test';
import * as assert from 'node:assert/strict';
import * as cdk from 'aws-cdk-lib';
import {Template,Match} from 'aws-cdk-lib/assertions';
import {GitHubStagingStack} from '../lib/github-staging-stack';
import {directStagingSynthesizer} from '../lib/staging-synthesizer';
test('direct credentials preserve templates and omit bootstrap role chaining',()=>{const make=(direct:boolean)=>{const app=new cdk.App();const stack=new cdk.Stack(app,'same',{env:{account:'559054714699',region:'us-east-1'},...(direct?{synthesizer:directStagingSynthesizer()}:{})});new cdk.CfnResource(stack,'Synthetic',{type:'AWS::S3::Bucket'});return {template:Template.fromStack(stack).toJSON(),artifact:app.synth().getStackArtifact(stack.artifactId)};};const normal=make(false),direct=make(true);assert.deepEqual(direct.template,normal.template);assert.ok(!direct.artifact.assumeRoleArn);assert.equal(direct.artifact.cloudFormationExecutionRoleArn,normal.artifact.cloudFormationExecutionRoleArn);});
test('OIDC is environment/audience scoped with no role chaining or IAM mutation',()=>{const t=Template.fromStack(new GitHubStagingStack(new cdk.App(),'test',{env:{account:'559054714699',region:'us-east-1'}}));t.hasResourceProperties('AWS::IAM::OIDCProvider',{Url:'https://token.actions.githubusercontent.com',ClientIdList:['sts.amazonaws.com']});t.hasResourceProperties('AWS::IAM::Role',{RoleName:'TracePointMigrationStagingGitHub',AssumeRolePolicyDocument:{Statement:Match.arrayWith([Match.objectLike({Action:'sts:AssumeRoleWithWebIdentity',Condition:{StringEquals:{'token.actions.githubusercontent.com:aud':'sts.amazonaws.com','token.actions.githubusercontent.com:sub':'repo:jphares65/tracepoint:environment:aws-staging'}}})])}});const policies=Object.values(t.findResources('AWS::IAM::Policy')) as any[];const actions=policies.flatMap(p=>p.Properties.PolicyDocument.Statement.flatMap((s:any)=>s.Action));assert.ok(!actions.includes('sts:AssumeRole'));assert.ok(!actions.some((a:string)=>a==='*'||a.endsWith(':*')||/^iam:(Create|Update|Put|Attach)/.test(a)));assert.throws(()=>new GitHubStagingStack(new cdk.App(),'bad',{env:{account:'265544358665',region:'us-east-1'}}));});

test('source encryption permission is limited to the staging build key through S3',()=>{const t=Template.fromStack(new GitHubStagingStack(new cdk.App(),'keytest',{env:{account:'559054714699',region:'us-east-1'}}));t.hasResourceProperties('AWS::IAM::Policy',{PolicyDocument:{Statement:Match.arrayWith([Match.objectLike({Action:['kms:GenerateDataKey','kms:Decrypt'],Resource:'arn:aws:kms:us-east-1:559054714699:key/e1fa82f6-045b-41a8-bfff-d3f57b17e710',Condition:{StringEquals:{'kms:ViaService':'s3.us-east-1.amazonaws.com'},ArnEquals:{'kms:EncryptionContext:aws:s3:arn':['arn:aws:s3:::tracepoint-staging-build-source-559054714699','arn:aws:s3:::tracepoint-staging-build-source-559054714699/source/tracepoint-staging-source.zip']}}})])}});});

test('rollback may pass only the two staging ECS roles to ECS tasks',()=>{const t=Template.fromStack(new GitHubStagingStack(new cdk.App(),'rollback',{env:{account:'559054714699',region:'us-east-1'}}));t.hasResourceProperties('AWS::IAM::Policy',{PolicyDocument:{Statement:Match.arrayWith([Match.objectLike({Action:'iam:PassRole',Resource:['arn:aws:iam::559054714699:role/tracepoint-staging-ecs-execution','arn:aws:iam::559054714699:role/tracepoint-staging-ecs-task'],Condition:{StringEquals:{'iam:PassedToService':'ecs-tasks.amazonaws.com'}}})])}});});
