import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { CLEAN_TARGET_HOST, CONNECTION_PROBE_MODE, COPY_RELATIONS, DATABASE_MODES, DEPARTMENT_PREREQUISITE_BOOTSTRAP_RELATIONS, DERIVED_RELATIONS, FEATURE_CATALOG_NON_AUTHORITATIVE_COLUMNS, FIREARM_ASSIGNMENTS_SCHEMA_REPAIR, IDENTITY_PRESERVATION_RELATIONS, IMPORT_RELATIONS, INITIAL_ARTIFACT_BUCKET, INITIAL_ARTIFACT_KEY, INITIAL_ARTIFACT_SHA256, NULLABLE_TRAINING_CERTIFICATION_CYCLE, OBJECT_MANIFEST, ROLE_PERMISSIONS_RECONCILIATION_MODE, SCHEMA_REPAIR_MODE, SCHEMA_SWEEP_MODE, TARGET_DATA_PREFLIGHT_MODE, TARGET_GENERATED_COLUMN_DIAGNOSTIC_MODE, TARGET_PROVENANCE_SWEEP_MODE, TARGET_SCHEMA_CONTRACT_MODE, TARGET_SEEDED_REFERENCE_RELATIONS, TARGET_HOST, assertDiagnosticReadOnlySql, auditPrerequisitePlan, canonicalRowsHash, classifyArtifactResumeRelation, classifyDepartmentPrerequisiteBootstrap, classifySourceOnlyColumn, classifyTargetGeneratedInput, classifyTargetOnlyColumn, compareSourceColumns, executeNullableTrainingCertificationCycle, identityPreservingInsertSql, insertSql, migrationAnchorProfileSemanticHash, nullableTrainingCertificationCyclePlan, objectManifestSha256, quote, reconcileExactTargetSeededRelation, reconcileFeatureCatalog, reconcileRolePermissionDifferences, requireExactTargetSeededParity, requireIdentityPreservationPreflight, requireMigrationAnchorProfileParity, requireTargetSeededFeatureCatalogParity, requireTargetSeededRolePermissionRule, requiredAuditDepartmentParents, sourceColumns, summarizeSourceColumn, topologicalImportOrder, updateByIdSql, validateColumnMapping, validateImportInvocation, validateObjectBytes, verifyIdentitySequenceAdvance, withRetainedDeadline } from "./supabase-rest-import-core.mjs";

test("the import contract excludes only derived views and target-seeded feature catalog", () => { assert.ok(DERIVED_RELATIONS.every(name => name.startsWith("v_"))); assert.ok(COPY_RELATIONS.every(name => !name.startsWith("v_"))); assert.equal(COPY_RELATIONS.length + DERIVED_RELATIONS.length, 90); assert.equal(IMPORT_RELATIONS.includes("feature_catalog"), false); });
test("import invocation is bound to the one reviewed production run and target", () => { const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",SOURCE_SUPABASE_REST_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/migration/source-supabase-rest-wvh4pi",TRACEPOINT_REST_IMPORT_MODE:"database",TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:TARGET_HOST,TARGET_PGDATABASE:"tracepoint"}; assert.doesNotThrow(()=>validateImportInvocation(base,"database")); assert.throws(()=>validateImportInvocation({...base,TARGET_PGHOST:"other"},"database")); });
test("artifact import is pinned to the adopted baseline without a Supabase secret", () => { const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",TRACEPOINT_REST_IMPORT_MODE:"database",TRACEPOINT_SOURCE_MODE:"immutable-artifact",TRACEPOINT_SOURCE_ARTIFACT_BUCKET:INITIAL_ARTIFACT_BUCKET,TRACEPOINT_SOURCE_ARTIFACT_KEY:INITIAL_ARTIFACT_KEY,TRACEPOINT_SOURCE_ARTIFACT_SHA256:INITIAL_ARTIFACT_SHA256,TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:CLEAN_TARGET_HOST,TARGET_PGDATABASE:"tracepoint"}; assert.doesNotThrow(()=>validateImportInvocation(base,"database")); assert.throws(()=>validateImportInvocation({...base,TRACEPOINT_SOURCE_ARTIFACT_SHA256:"f".repeat(64)},"database")); });
test("quarantined clean target is the only additional reviewed endpoint", () => { const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",SOURCE_SUPABASE_REST_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/migration/source-supabase-rest-wvh4pi",TRACEPOINT_REST_IMPORT_MODE:"database",TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:CLEAN_TARGET_HOST,TARGET_PGDATABASE:"tracepoint"}; assert.doesNotThrow(()=>validateImportInvocation(base,"database")); assert.throws(()=>validateImportInvocation({...base,TARGET_PGHOST:"other.c8r4sgs089tu.us-east-1.rds.amazonaws.com"},"database")); const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"); assert.match(runner,/validateImportInvocation/); assert.match(runner,/host: process\.env\.TARGET_PGHOST/); });
test("generated-column diagnostic is target-bound and accepts only read-only SQL", () => { const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",SOURCE_SUPABASE_REST_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/migration/source-supabase-rest-wvh4pi",TRACEPOINT_REST_IMPORT_MODE:TARGET_GENERATED_COLUMN_DIAGNOSTIC_MODE,TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:TARGET_HOST,TARGET_PGDATABASE:"tracepoint"}; assert.doesNotThrow(()=>validateImportInvocation(base,TARGET_GENERATED_COLUMN_DIAGNOSTIC_MODE)); for(const sql of ["select 1","with x as (select 1) select * from x","begin transaction isolation level repeatable read read only","commit","rollback"]) assert.doesNotThrow(()=>assertDiagnosticReadOnlySql(sql)); for(const sql of ["insert into public.x values (1)","update public.x set a=1","delete from public.x","alter table public.x add column a int"]) assert.throws(()=>assertDiagnosticReadOnlySql(sql),/DIAGNOSTIC_SQL_NOT_READ_ONLY/); });
test("generated-column diagnostic initializes no target mutation path", () => { const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"),start=runner.indexOf("async function runTargetGeneratedColumnDiagnostic()"),end=runner.indexOf("async function targetRows",start); assert.ok(start>=0&&end>start); const body=runner.slice(start,end); assert.match(body,/begin transaction isolation level repeatable read read only/); assert.match(body,/targetWriteClientsInitialized: false/); assert.match(body,/assertDiagnosticReadOnlySql/); assert.doesNotMatch(body,/\b(insert|update|merge|truncate|alter|create|drop|grant|revoke|call|do|copy|setval)\b/i); assert.doesNotMatch(body,/\bS3Client\b|\bPutObjectCommand\b|\bCognito\b/); });
test("provenance sweep is target-bound and contains no mutation path", () => { const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",SOURCE_SUPABASE_REST_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/migration/source-supabase-rest-wvh4pi",TRACEPOINT_REST_IMPORT_MODE:TARGET_PROVENANCE_SWEEP_MODE,TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:TARGET_HOST,TARGET_PGDATABASE:"tracepoint"}; assert.ok(DATABASE_MODES.includes(TARGET_PROVENANCE_SWEEP_MODE)); assert.doesNotThrow(()=>validateImportInvocation(base,TARGET_PROVENANCE_SWEEP_MODE)); const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"),start=runner.indexOf("async function runTargetProvenanceSweep()"),end=runner.indexOf("async function runTargetDataPreflight()",start),body=runner.slice(start,end); assert.ok(start>=0&&end>start); assert.match(body,/begin transaction isolation level repeatable read read only/); assert.match(body,/targetWriteClientsInitialized: false/); assert.match(body,/assertDiagnosticReadOnlySql/); assert.doesNotMatch(body,/\b(insert|update|merge|truncate|alter|create|drop|grant|revoke|call|do|copy|setval)\b/i); assert.doesNotMatch(body,/\bS3Client\b|\bPutObjectCommand\b|\bCognito\b/); });
test("audit identity collision diagnostic is read-only and covers exactly both preserved-ID relations", () => { const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"),start=runner.indexOf("async function auditIdentityDiagnostic()"),end=runner.indexOf("async function runReviewedMode()",start),body=runner.slice(start,end); assert.ok(start>=0&&end>start); assert.match(body,/begin transaction isolation level repeatable read read only/); assert.match(body,/IDENTITY_PRESERVATION_RELATIONS/); assert.match(body,/targetWriteClientsInitialized:false/); assert.doesNotMatch(body,/\b(insert|update|merge|truncate|alter|create|drop|grant|revoke|call|do|copy|setval)\b/i); });
test("reviewed runner keeps Node alive until its sanitized mode result is emitted", () => { const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"); assert.match(runner,/const reviewedModeLiveness = setInterval/); assert.match(runner,/await runReviewedMode\(\)/); assert.match(runner,/clearInterval\(reviewedModeLiveness\)/); });
test("connection probe is target-only, bounded, TLS-required, and read-only", () => {
  const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",SOURCE_SUPABASE_REST_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/migration/source-supabase-rest-wvh4pi",TRACEPOINT_REST_IMPORT_MODE:CONNECTION_PROBE_MODE,TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:CLEAN_TARGET_HOST,TARGET_PGDATABASE:"tracepoint"};
  assert.ok(DATABASE_MODES.includes(CONNECTION_PROBE_MODE)); assert.doesNotThrow(()=>validateImportInvocation(base,CONNECTION_PROBE_MODE));
  const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"),start=runner.indexOf("async function runConnectionProbe()"),end=runner.indexOf("async function runReviewedMode()",start),body=runner.slice(start,end);
  assert.ok(start>=0&&end>start); assert.match(runner,/rejectUnauthorized: true/); assert.match(body,/begin transaction read only/); assert.match(body,/select 1 as ok/); assert.match(body,/show transaction_read_only/); assert.match(body,/select current_database\(\) as database, current_user as user/); assert.match(body,/sourceClientsInitialized: false/); assert.doesNotMatch(body,/sourceSnapshot|allRelationRows|allAdminUsers|S3Client|PutObjectCommand|\b(insert|update|alter|create|drop|grant|revoke|copy)\b/i);
});
test("retained connection deadline completes normally and fails closed when stalled", async () => {
  const events=[]; assert.equal(await withRetainedDeadline({phase:"dns-resolution",deadlineMs:100,operation:async()=>"ok",onEvent:event=>events.push(event)}),"ok"); assert.deepEqual(events.map(event=>event.event),["connection-probe-phase-start","connection-probe-phase-complete"]);
  const started=Date.now(); await assert.rejects(()=>withRetainedDeadline({phase:"tcp-tls-postgresql-connect",deadlineMs:25,operation:()=>new Promise(()=>undefined)}),/CONNECTION_PROBE_TIMEOUT/); assert.ok(Date.now()-started<250);
});
test("audit-first preflight bounds every target lifecycle phase and leaves write paths unreachable", () => {
  const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"),start=runner.indexOf("async function runTargetDataPreflight()"),end=runner.indexOf("async function querySchemaContract",start),body=runner.slice(start,end);
  assert.ok(start>=0&&end>start); for(const event of ["target-dns","target-connect","target-readonly","audit-table-query","post-source-06","post-source-08","post-source-09"]) assert.match(body,new RegExp(`eventPrefix: \\"${event}\\"`));
  for(const marker of ["post-source-00","post-source-07","post-source-10"]) assert.match(body,new RegExp(`event: \\"${marker}\\"`));
  assert.ok(body.indexOf("sourceSnapshot(event => emit(event))") < body.indexOf("client = targetClient")); assert.match(body,/begin transaction isolation level repeatable read read only/); assert.match(body,/assertDiagnosticReadOnlySql/); assert.match(body,/targetWriteClientsInitialized: false/); assert.doesNotMatch(body,/\b(insert|update|delete\s+from|alter|create|drop|grant|revoke|copy)\b/i);
});
test("source snapshot emits sanitized completion markers before it returns", () => {
  const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"),start=runner.indexOf("async function sourceSnapshot("),end=runner.indexOf("function jsonRows",start),body=runner.slice(start,end);
  assert.ok(start>=0&&end>start); for(const marker of ["post-source-01","post-source-02","post-source-03","post-source-04","post-source-05"]) assert.match(body,new RegExp(`event: \\"${marker}\\"`)); assert.doesNotMatch(body,/password|serviceRoleKey|row\./i);
});
test("generated and identity conflicts are classified without source values", () => { const stats={sourceColumn:"id",rowCount:2,populatedRowCount:2,nullOrMissingRowCount:0,distinctValueCount:2,observedJsonTypeCounts:{string:2}}; const generated=classifyTargetGeneratedInput("departments",stats,{column_name:"id",data_type:"uuid",is_identity:"NO",identity_generation:null,is_generated:"ALWAYS",generation_expression:"generated",column_default:null,sequence_name:null}); assert.equal(generated.classification,"UNKNOWN_CONFLICT"); assert.equal(generated.acceptsExplicitSourceValue,false); assert.deepEqual(generated.sourceStatistics,stats); const identity=classifyTargetGeneratedInput("departments",stats,{column_name:"id",data_type:"bigint",is_identity:"YES",identity_generation:"ALWAYS",is_generated:"NEVER",generation_expression:null,column_default:null,sequence_name:null}); assert.equal(identity.classification,"SOURCE_AUTHORITATIVE_MUST_PRESERVE"); assert.equal(identity.acceptsExplicitSourceValue,false); });
test("known migration-anchor timestamp provenance is the only automatic generated classification", () => { const stats={sourceColumn:"updated_at",rowCount:1,populatedRowCount:1,nullOrMissingRowCount:0,distinctValueCount:1,observedJsonTypeCounts:{string:1}}; const result=classifyTargetGeneratedInput("profiles",stats,{column_name:"updated_at",data_type:"timestamp with time zone",is_identity:"NO",identity_generation:null,is_generated:"NEVER",generation_expression:null,column_default:"now()",sequence_name:null},["profiles_set_updated_at"]); assert.equal(result.classification,"TARGET_GENERATED_EXCLUDE_FROM_IMPORT"); const other=classifyTargetGeneratedInput("departments",{...stats,sourceColumn:"updated_at"},{column_name:"updated_at",data_type:"timestamp with time zone",is_identity:"NO",identity_generation:null,is_generated:"NEVER",generation_expression:null,column_default:"now()",sequence_name:null},["unknown_trigger"]); assert.equal(other.classification,null); });
test("only the two approved audit relations emit overriding system value", () => { assert.deepEqual(IDENTITY_PRESERVATION_RELATIONS,["audit_events","retired_permission_assignment_audit"]); for(const relation of IDENTITY_PRESERVATION_RELATIONS) assert.match(identityPreservingInsertSql(relation,["id","department_id"]),/overriding system value/i); assert.throws(()=>identityPreservingInsertSql("departments",["id"]),/NOT_ALLOWED/); assert.throws(()=>identityPreservingInsertSql("audit_events",["department_id"]),/ID_MISSING/); });
test("identity preservation preflight rejects collisions and duplicate source IDs", () => { const columns=[{column_name:"id",data_type:"bigint",is_identity:"YES",identity_generation:"ALWAYS"}],source=[{id:1,name:"one"},{id:2,name:"two"}]; const pass=requireIdentityPreservationPreflight("audit_events",source,[],columns); assert.equal(pass.sourceIdCount,2); assert.doesNotThrow(()=>requireIdentityPreservationPreflight("retired_permission_assignment_audit",source,[...source],columns)); assert.throws(()=>requireIdentityPreservationPreflight("audit_events",[{id:1},{id:1}],[],columns),/SOURCE_ID_DUPLICATE/); assert.throws(()=>requireIdentityPreservationPreflight("audit_events",source,[{id:1,name:"different"}],columns),/TARGET_ID_COLLISION/); assert.throws(()=>requireIdentityPreservationPreflight("audit_events",source,[{id:3,name:"other"}],columns),/TARGET_UNEXPLAINED/); });
test("identity sequence repair evidence must remain beyond imported IDs", () => { assert.deepEqual(verifyIdentitySequenceAdvance("audit_events","2659","2659"),{relation:"audit_events",lastValue:"2659",maxImportedId:"2659",nextGeneratedIdCannotCollide:true}); assert.throws(()=>verifyIdentitySequenceAdvance("retired_permission_assignment_audit","80","81"),/BEHIND/); });
test("artifact-aware resume retains exact rows, resets only proven partial artifacts, and fails closed", () => {
  const source=[{id:"a",department_id:"d",value:1},{id:"b",department_id:"d",value:2}];
  assert.equal(classifyArtifactResumeRelation({relation:"departments",sourceRows:source,targetRows:source,stableColumns:["id"]}).strategy,"retain-exact-source-match");
  const partial=classifyArtifactResumeRelation({relation:"departments",sourceRows:source,targetRows:[source[0]],stableColumns:["id"]});
  assert.equal(partial.strategy,"cleanup-and-import-full"); assert.equal(partial.classification,"partial-source-subset");
  const grants=[{department_id:"d",role_code:"officer",permission_code:"view",created_at:"source"},{department_id:"d",role_code:"officer",permission_code:"write",created_at:"source"}];
  const grantArtifact=classifyArtifactResumeRelation({relation:"department_role_permissions",sourceRows:grants,targetRows:[{...grants[0],created_at:"target"}],stableColumns:["department_id","role_code","permission_code"]});
  assert.equal(grantArtifact.classification,"partial-source-subset-with-reviewed-security-stable-keys");
  assert.throws(()=>classifyArtifactResumeRelation({relation:"department_role_permissions",sourceRows:grants,targetRows:[{...grants[0],permission_code:"admin"}],stableColumns:["department_id","role_code","permission_code"]}),/TARGET_UNEXPLAINED_ROWS/);
  assert.equal(classifyArtifactResumeRelation({relation:"department_rules",sourceRows:source,targetRows:[{...source[0],value:3},{...source[1],value:3}],stableColumns:["id"],generatedArtifactProven:true}).classification,"generated-migration-side-effect");
  assert.throws(()=>classifyArtifactResumeRelation({relation:"departments",sourceRows:source,targetRows:[{id:"unexpected",department_id:"d",value:1}],stableColumns:["id"]}),/TARGET_UNEXPLAINED_ROWS/);
  assert.throws(()=>classifyArtifactResumeRelation({relation:"department_rules",sourceRows:source,targetRows:[{...source[0],value:3},{...source[1],value:3}],stableColumns:["id"]}),/TARGET_UNEXPLAINED_ROWS/);
});
test("audit prerequisites are the complete safe transitive parent set and fail closed on audit writers", () => {
  const graph=[{child:"audit_events",parent:"departments"},{child:"audit_log",parent:"departments"},{child:"departments",parent:"organizations"}];
  const plan=auditPrerequisitePlan({importRelations:["organizations","departments","audit_events","audit_log","retired_permission_assignment_audit"],auditRelations:["audit_events","audit_log","retired_permission_assignment_audit"],foreignKeys:graph});
  assert.deepEqual(plan.prerequisiteRelations,["organizations","departments"]);
  assert.deepEqual(plan.classifications.map(item=>item.classification),["SAFE_PREREQUISITE_NO_AUDIT_SIDE_EFFECT","SAFE_PREREQUISITE_NO_AUDIT_SIDE_EFFECT"]);
  assert.throws(()=>auditPrerequisitePlan({importRelations:["audit_events"],auditRelations:["audit_events"],foreignKeys:[{child:"audit_events",parent:"missing_parent"}]}),/AUDIT_PREREQUISITE_PARENT_NOT_MANAGED/);
  assert.throws(()=>auditPrerequisitePlan({importRelations:["departments","audit_events"],auditRelations:["audit_events"],foreignKeys:[{child:"audit_events",parent:"departments"}],auditWritingRelations:["departments"]}),/AUDIT_PREREQUISITE_CAN_GENERATE_AUDIT:departments/);
  assert.throws(()=>auditPrerequisitePlan({importRelations:["departments","audit_events"],auditRelations:["audit_events"],foreignKeys:[{child:"audit_events",parent:"departments"}],auditWritingRelations:["departments"]}),/AUDIT_PREREQUISITE_CAN_GENERATE_AUDIT/);
  const reviewed=auditPrerequisitePlan({importRelations:["departments","audit_events"],auditRelations:["audit_events"],foreignKeys:[{child:"audit_events",parent:"departments"}],auditWritingRelations:["departments"],approvedBootstrapAuditRelations:["departments"]});
  assert.deepEqual(reviewed.classifications,[{relation:"departments",classification:"PREREQUISITE_CAN_GENERATE_AUDIT"}]);
});
test("department prerequisite selection is exact and source-audit parent gaps fail closed", () => {
  const departments=[{id:"d1"},{id:"d2"}], audit=[{id:1,department_id:"d2"},{id:2,department_id:"d1"}];
  assert.deepEqual(requiredAuditDepartmentParents(departments,audit).map(row=>row.id),["d1","d2"]);
  assert.throws(()=>requiredAuditDepartmentParents([{id:"d1"}],[{department_id:"d2"}]),/AUDIT_DEPARTMENT_PARENT_MISSING/);
});
test("department prerequisite bootstrap classification is relation-scoped and fails closed on unknown rows", () => {
  const departmentIds=["d1"], source=[{id:"r1",department_id:"d1",setting:"source"}];
  const result=classifyDepartmentPrerequisiteBootstrap({relation:"department_rules",sourceRows:source,generatedRows:[source[0],{id:"r2",department_id:"d1",setting:"generated"},{id:"r3",department_id:"d1",setting:"different"}],departmentIds,stableColumns:["id"]});
  assert.deepEqual(DEPARTMENT_PREREQUISITE_BOOTSTRAP_RELATIONS,["audit_events","department_rules","department_security_settings","department_role_permissions"]);
  assert.deepEqual(result.classificationCounts,{EXACT_CANONICAL_SOURCE_MATCH:1,GENERATED_BOOTSTRAP_ARTIFACT_CONFLICTING_WITH_SOURCE:0,GENERATED_BOOTSTRAP_ARTIFACT_WITH_NO_SOURCE_ROW:2});
  assert.throws(()=>classifyDepartmentPrerequisiteBootstrap({relation:"department_rules",sourceRows:source,generatedRows:[{id:"x",department_id:"other"}],departmentIds,stableColumns:["id"]}),/UNEXPLAINED_TARGET_ROW/);
  assert.throws(()=>classifyDepartmentPrerequisiteBootstrap({relation:"profiles",sourceRows:[],generatedRows:[],departmentIds,stableColumns:["id"]}),/DEPARTMENT_BOOTSTRAP_RELATION_INVALID/);
});
test("audit-first runner creates audit-neutral identity/profile anchors before the reviewed department bootstrap cleanup", () => { const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"), start=runner.indexOf("async function runDatabase()"), body=runner.slice(start,runner.indexOf("async function runFeatureCatalogReconciliation()",start)); assert.match(body,/requireIdentityAnchorPrerequisites/); assert.match(body,/insertIdentityAnchors\(client, snapshot\.users\)/); assert.match(body,/assertAuditHistoryEmpty\(client, "before_identity_anchor_creation"\)/); assert.match(body,/assertAuditHistoryEmpty\(client, "before_department_prerequisite_bootstrap"\)/); assert.match(body,/assertAuditHistoryEmpty\(client, "before_source_history"\)/); assert.ok(body.indexOf('"identity anchors\/profile shells"') < body.indexOf('"department prerequisite bootstrap cleanup"')); assert.ok(body.indexOf('"department prerequisite bootstrap cleanup"') < body.indexOf('"source audit history"')); assert.ok(body.indexOf('"source audit history"') < body.indexOf('"relational import"')); assert.ok(body.indexOf('"audit identity sequence repair"') < body.indexOf('"relational import"')); const anchors=runner.slice(runner.indexOf("async function insertIdentityAnchors"),runner.indexOf("async function hydrateMigrationAnchorProfiles")); assert.match(anchors,/TARGET_PROFILE_SHELL_PREEXISTS/); assert.match(anchors,/TARGET_PROFILE_SHELL_ID_SET_MISMATCH/); assert.match(anchors,/assertAuditHistoryEmpty\(client, "after_identity_anchor_creation"\)/); const cleanup=runner.slice(runner.indexOf("async function runDepartmentPrerequisiteBootstrapCleanup"),runner.indexOf("async function insertIdentityAnchors")); assert.ok(cleanup.indexOf('delete from public.${relation}') < cleanup.indexOf('delete from public.audit_events')); assert.match(cleanup,/PREREQUISITE_AUDIT_NOT_EMPTY_AFTER_CLEANUP/); });
test("target-seeded feature catalog permits only reviewed bootstrap metadata differences", () => { const source=[{code:"analytics",display_name:"Analytics source",description:"source",sort_order:2,is_active:true,created_at:"2026-01-01T00:00:00Z"}]; const target=[{code:"analytics",display_name:"Analytics target",description:null,sort_order:20,is_active:true,created_at:"2026-02-01T00:00:00Z"}]; const result=requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog(source,target,["code","display_name","description","sort_order","is_active","created_at"])); assert.deepEqual(FEATURE_CATALOG_NON_AUTHORITATIVE_COLUMNS,["created_at"]); assert.equal(result.rows[0].classification,"target-seeded reference data — excluded by design"); assert.equal(result.rows[0].isActiveParity,true); assert.throws(()=>insertSql("feature_catalog",["code"])); });
test("target-seeded feature catalog fails closed for code-set or active-state drift", () => { const source=[{code:"analytics",display_name:"Analytics",description:null,sort_order:20,is_active:true,created_at:"2026-01-01T00:00:00Z"}]; const target=[{...source[0],is_active:false}]; assert.throws(()=>requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog(source,target,["code","display_name","description","sort_order","is_active","created_at"])),/ACTIVE_STATE/); assert.throws(()=>requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog(source,[],["code"])),/SOURCE_ONLY/); assert.throws(()=>requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog([],source,["code"])),/TARGET_ONLY/); });
test("target-seeded authorization catalogs require exact stable-key and semantic parity", () => { const source=[{role_code:"officer",permission_code:"view"},{role_code:"chief",permission_code:"manage"}], target=[{role_code:"chief",permission_code:"manage"},{role_code:"officer",permission_code:"view"}]; assert.doesNotThrow(()=>requireExactTargetSeededParity(reconcileExactTargetSeededRelation("role_permissions",source,target,["role_code","permission_code"]))); assert.throws(()=>requireExactTargetSeededParity(reconcileExactTargetSeededRelation("role_permissions",source,[{role_code:"officer",permission_code:"other"}],["role_code","permission_code"])),/STABLE_KEY/); assert.deepEqual(TARGET_SEEDED_REFERENCE_RELATIONS,["feature_catalog","roles","permissions","role_permissions"]); assert.ok(DATABASE_MODES.includes(TARGET_DATA_PREFLIGHT_MODE)); });
test("role-permission reconciliation identifies exact unmatched stable pairs without a merge rule", () => { const source=[{role_code:"chief",permission_code:"manage"},{role_code:"officer",permission_code:"view"},{role_code:"officer",permission_code:"audit"}], target=[{role_code:"chief",permission_code:"manage"},{role_code:"officer",permission_code:"view"}]; const result=reconcileRolePermissionDifferences(source,target); assert.equal(result.exactMatchCount,2); assert.deepEqual(result.sourceOnly,[{roleCode:"officer",permissionCode:"audit"}]); assert.deepEqual(result.targetOnly,[]); assert.equal(result.stableKeyParity,false); assert.ok(DATABASE_MODES.includes(ROLE_PERMISSIONS_RECONCILIATION_MODE)); assert.throws(()=>reconcileRolePermissionDifferences([{role_code:"officer",permission_code:"view"},{role_code:"officer",permission_code:"view"}],[]),/DUPLICATE/); });
test("the target-owned role-permission rule accepts only the five reviewed global defaults", () => { const target=[{role_code:"administrator",permission_code:"administer_department"}]; const source=[...target,{role_code:"administrator",permission_code:"manage_certifications"},{role_code:"administrator",permission_code:"manage_equipment"},{role_code:"supervisor",permission_code:"manage_certifications"},{role_code:"supervisor",permission_code:"manage_equipment"},{role_code:"supervisor",permission_code:"manage_training"}]; const reconciliation=requireTargetSeededRolePermissionRule(reconcileRolePermissionDifferences(source,target)); assert.equal(reconciliation.classification,"target-seeded reference data — excluded by design"); assert.throws(()=>requireTargetSeededRolePermissionRule(reconcileRolePermissionDifferences([...source,{role_code:"supervisor",permission_code:"manage_users"}],target)),/UNREVIEWED_SOURCE_ONLY/); assert.throws(()=>requireTargetSeededRolePermissionRule(reconcileRolePermissionDifferences(source,[...target,{role_code:"officer",permission_code:"submit"}])),/TARGET_ONLY/); });
test("schema-contract helpers emit aggregate-only source evidence and safe target classifications", () => { const rows=[{id:"a",legacy_note:null},{id:"b",legacy_note:"present"}]; assert.deepEqual(summarizeSourceColumn(rows,"legacy_note"),{sourceColumn:"legacy_note",rowCount:2,populatedRowCount:1,nullOrMissingRowCount:1,distinctValueCount:1,observedJsonTypeCounts:{string:1}}); assert.equal(classifyTargetOnlyColumn({column_name:"created_at",is_identity:false,column_default:"now()",is_nullable:"NO"}),"TARGET_DEFAULTED"); assert.equal(classifyTargetOnlyColumn({column_name:"required",is_identity:false,column_default:null,is_nullable:"NO"}),"REQUIRED_IMPORT_VALUE"); });
test("the approved firearm schema repair is exact and the source-only field cannot be dropped", () => { assert.deepEqual(FIREARM_ASSIGNMENTS_SCHEMA_REPAIR.statements,["ALTER TABLE public.firearm_assignments ADD COLUMN magazines_expected_return integer","ALTER TABLE public.firearm_assignments ADD CONSTRAINT firearm_assignments_magazines_expected_return_nonnegative CHECK (magazines_expected_return IS NULL OR magazines_expected_return >= 0) NOT VALID"]); assert.equal(classifySourceOnlyColumn("firearm_assignments","magazines_expected_return",{sourceColumn:"magazines_expected_return"}),"TARGET_SCHEMA_MISSING_COLUMN"); assert.ok(DATABASE_MODES.includes(SCHEMA_REPAIR_MODE)); assert.ok(DATABASE_MODES.includes(SCHEMA_SWEEP_MODE)); });
test("target schema-contract mode is artifact-backed and cannot access data or mutation paths", () => {
  const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",TRACEPOINT_REST_IMPORT_MODE:TARGET_SCHEMA_CONTRACT_MODE,TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:CLEAN_TARGET_HOST,TARGET_PGDATABASE:"tracepoint",TRACEPOINT_SOURCE_MODE:"immutable-artifact",TRACEPOINT_SOURCE_ARTIFACT_BUCKET:INITIAL_ARTIFACT_BUCKET,TRACEPOINT_SOURCE_ARTIFACT_KEY:INITIAL_ARTIFACT_KEY,TRACEPOINT_SOURCE_ARTIFACT_SHA256:INITIAL_ARTIFACT_SHA256};
  assert.ok(DATABASE_MODES.includes(TARGET_SCHEMA_CONTRACT_MODE)); assert.doesNotThrow(()=>validateImportInvocation(base,TARGET_SCHEMA_CONTRACT_MODE));
  const runner=readFileSync(new URL("./run-supabase-rest-initial-import.mjs",import.meta.url),"utf8"),start=runner.indexOf("async function runTargetSchemaContract()"),end=runner.indexOf("function assertSourceObjectUrl",start),body=runner.slice(start,end);
  assert.ok(start>=0&&end>start); assert.match(runner,/table_schema='public' and table_name='firearm_assignments'/); assert.match(body,/begin transaction isolation level repeatable read read only/); assert.match(body,/assertDiagnosticReadOnlySql/); assert.match(body,/sourceClientsInitialized: false/); assert.match(body,/targetWriteClientsInitialized: false/); assert.doesNotMatch(body,/allRelationRows\(|allAdminUsers\(|headers|client\.query\(\s*["`](?:insert|update|delete|alter|create|drop|grant|revoke|copy)/i);
});
test("source equivalence check proves a mapping without emitting source values", () => { const result=compareSourceColumns([{legacy:2,current:2},{legacy:2,current:2},{legacy:null,current:null}],"legacy","current"); assert.deepEqual(result,{leftColumn:"legacy",rightColumn:"current",rowCount:3,equalRowCount:3,unequalRowCount:0,bothPopulatedRowCount:2,leftOnlyPopulatedRowCount:0,rightOnlyPopulatedRowCount:0,bothNullOrMissingRowCount:1}); });
test("source-target mappings allow only exact safe source columns and parameterized inserts", () => { const columns=[{column_name:"id",is_nullable:"NO",column_default:null,is_identity:false},{column_name:"name",is_nullable:"YES",column_default:null,is_identity:false}]; const mapping=validateColumnMapping("departments",[{id:"a",name:"dept"}],columns); assert.deepEqual(mapping.mapping,{id:"id",name:"name"}); assert.match(insertSql("departments",["id","name"]),/\$1::json/); assert.throws(()=>sourceColumns([{bad:"x", "unsafe-key":"no"}])); assert.throws(()=>quote("bad;drop")); });
test("migration-anchor profile hydration has an ID-bound update and cannot insert", () => { const sql=updateByIdSql("profiles",["id","email","display_name"]); assert.match(sql,/update public\."profiles" as target/); assert.match(sql,/where target\."id"=source\."id"/); assert.doesNotMatch(sql,/insert/i); assert.throws(()=>updateByIdSql("profiles",["email"])); });
test("only proven migration-anchor profiles exclude target-generated timestamps", () => { const source=[{id:"p1",email:"p@example.test",full_name:"Pat",created_at:"2020-01-01",updated_at:"2020-01-02"}], target=[{id:"p1",email:"p@example.test",full_name:"Pat",created_at:"2026-01-01",updated_at:"2026-01-02"}]; const result=requireMigrationAnchorProfileParity(source,target,true); assert.equal(result.semanticCanonicalSha256,migrationAnchorProfileSemanticHash(target)); assert.throws(()=>requireMigrationAnchorProfileParity(source,[{...target[0],email:"other@example.test"}],true),/NON_GENERATED/); assert.throws(()=>requireMigrationAnchorProfileParity(source,target,false),/NOT_MIGRATION_ANCHORS/); assert.doesNotThrow(()=>requireMigrationAnchorProfileParity(source,target,true)); });
test("foreign-key ordering is deterministic and cycles fail closed", () => { assert.deepEqual(topologicalImportOrder(["a","b","c"],[{child:"b",parent:"a"},{child:"c",parent:"b"}]),["a","b","c"]); assert.throws(()=>topologicalImportOrder(["a","b"],[{child:"a",parent:"b"},{child:"b",parent:"a"}]),/CYCLE/); });
const cycleRows = (overrides={}) => new Map([
  ["departments", [{id:"d1",department_id:"d1"}]],
  ["agency_training_attendees", [{id:"a1",department_id:"d1",certification_id:"c1",...overrides.attendee}]],
  ["training_certifications", [{id:"c1",department_id:"d1",source_training_attendee_id:"a1",...overrides.certification}]],
]);
const cycleRelations = ["departments","agency_training_attendees","training_certifications"];
const cycleForeignKeys = [
  {child:"agency_training_attendees",parent:"departments"}, {child:"training_certifications",parent:"departments"},
  {child:"agency_training_attendees",parent:"training_certifications"}, {child:"training_certifications",parent:"agency_training_attendees"},
];
test("two-phase nullable cycle preserves exact links while masking only phase-one values", () => {
  const plan=nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows());
  assert.deepEqual(plan.order,["departments",NULLABLE_TRAINING_CERTIFICATION_CYCLE.token]);
  assert.equal(plan.phaseOne.attendees[0].certification_id,null); assert.equal(plan.phaseOne.certifications[0].source_training_attendee_id,null);
  assert.equal(plan.restore.attendees[0].value,"c1"); assert.equal(plan.restore.certifications[0].value,"a1");
});
test("two-phase nullable cycle preserves source nulls without restoration", () => {
  const plan=nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({attendee:{certification_id:null},certification:{source_training_attendee_id:null}}));
  assert.equal(plan.restore.attendees[0].value,null); assert.equal(plan.restore.certifications[0].value,null);
});
test("two-phase nullable cycle fails closed for missing references and cross-tenant links", () => {
  assert.throws(()=>nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({attendee:{certification_id:"missing"}})),/CERTIFICATION_REFERENCE_MISSING/);
  assert.throws(()=>nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({certification:{department_id:"d2"}})),/CROSS_DEPARTMENT_CERTIFICATION_REFERENCE/);
});
test("two-phase nullable cycle fails closed for a missing attendee reference and any additional graph cycle", () => {
  assert.throws(()=>nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({certification:{source_training_attendee_id:"missing"}})),/ATTENDEE_REFERENCE_MISSING/);
  assert.throws(()=>nullableTrainingCertificationCyclePlan([...cycleRelations,"other_a","other_b"],[...cycleForeignKeys,{child:"other_a",parent:"other_b"},{child:"other_b",parent:"other_a"}],cycleRows()),/TARGET_FOREIGN_KEY_CYCLE/);
});
test("two-phase nullable cycle rolls back if a second-phase restoration fails", async () => {
  const plan=nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows()); const calls=[];
  await assert.rejects(()=>executeNullableTrainingCertificationCycle(plan,{begin:async()=>calls.push("begin"),insertAttendees:async()=>calls.push("insert-attendees"),insertCertifications:async()=>calls.push("insert-certifications"),restoreAttendees:async()=>calls.push("restore-attendees"),restoreCertifications:async()=>{calls.push("restore-certifications");throw Error("fail");},validate:async()=>calls.push("validate"),commit:async()=>calls.push("commit"),rollback:async()=>calls.push("rollback")}));
  assert.deepEqual(calls,["begin","insert-attendees","insert-certifications","restore-attendees","restore-certifications","rollback"]);
});
test("the object manifest is fixed, checksum complete, and tenant scoped", () => { assert.equal(OBJECT_MANIFEST.length,2); assert.match(objectManifestSha256,/^[0-9a-f]{64}$/); for(const object of OBJECT_MANIFEST){assert.ok(object.destinationKey.startsWith(`department-assets/${object.departmentId}/`)); assert.throws(()=>validateObjectBytes(object,new Uint8Array(0)),/SIZE/);} assert.notEqual(canonicalRowsHash([{a:1}]),canonicalRowsHash([{a:2}])); });
