import assert from "node:assert/strict";
import test from "node:test";
import { COPY_RELATIONS, DATABASE_MODES, DERIVED_RELATIONS, FEATURE_CATALOG_NON_AUTHORITATIVE_COLUMNS, FIREARM_ASSIGNMENTS_SCHEMA_REPAIR, IMPORT_RELATIONS, NULLABLE_TRAINING_CERTIFICATION_CYCLE, OBJECT_MANIFEST, ROLE_PERMISSIONS_RECONCILIATION_MODE, SCHEMA_REPAIR_MODE, SCHEMA_SWEEP_MODE, TARGET_DATA_PREFLIGHT_MODE, TARGET_SEEDED_REFERENCE_RELATIONS, TARGET_HOST, canonicalRowsHash, classifySourceOnlyColumn, classifyTargetOnlyColumn, compareSourceColumns, executeNullableTrainingCertificationCycle, insertSql, nullableTrainingCertificationCyclePlan, objectManifestSha256, quote, reconcileExactTargetSeededRelation, reconcileFeatureCatalog, reconcileRolePermissionDifferences, requireExactTargetSeededParity, requireTargetSeededFeatureCatalogParity, requireTargetSeededRolePermissionRule, sourceColumns, summarizeSourceColumn, topologicalImportOrder, validateColumnMapping, validateImportInvocation, validateObjectBytes } from "./supabase-rest-import-core.mjs";

test("the import contract excludes only derived views and target-seeded feature catalog", () => { assert.ok(DERIVED_RELATIONS.every(name => name.startsWith("v_"))); assert.ok(COPY_RELATIONS.every(name => !name.startsWith("v_"))); assert.equal(COPY_RELATIONS.length + DERIVED_RELATIONS.length, 90); assert.equal(IMPORT_RELATIONS.includes("feature_catalog"), false); });
test("import invocation is bound to the one reviewed production run and target", () => { const base={TRACEPOINT_MIGRATION_RUN_ID:"4272874f-bae4-49f4-a0b4-67a39cec2874",TRACEPOINT_MIGRATION_AUTHORIZATION_REFERENCE:"TP-FINAL-DB-20260920-4272874FBAE4",TRACEPOINT_EXPECTED_AWS_ACCOUNT:"193644343389",SOURCE_SUPABASE_REST_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/migration/source-supabase-rest-wvh4pi",TRACEPOINT_REST_IMPORT_MODE:"database",TARGET_DATABASE_SECRET_ARN:"arn:aws:secretsmanager:us-east-1:193644343389:secret:tracepoint/production/database/migrator-8X57JT",TARGET_PGHOST:TARGET_HOST,TARGET_PGDATABASE:"tracepoint"}; assert.doesNotThrow(()=>validateImportInvocation(base,"database")); assert.throws(()=>validateImportInvocation({...base,TARGET_PGHOST:"other"},"database")); });
test("target-seeded feature catalog permits only reviewed bootstrap metadata differences", () => { const source=[{code:"analytics",display_name:"Analytics source",description:"source",sort_order:2,is_active:true,created_at:"2026-01-01T00:00:00Z"}]; const target=[{code:"analytics",display_name:"Analytics target",description:null,sort_order:20,is_active:true,created_at:"2026-02-01T00:00:00Z"}]; const result=requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog(source,target,["code","display_name","description","sort_order","is_active","created_at"])); assert.deepEqual(FEATURE_CATALOG_NON_AUTHORITATIVE_COLUMNS,["created_at"]); assert.equal(result.rows[0].classification,"target-seeded reference data — excluded by design"); assert.equal(result.rows[0].isActiveParity,true); assert.throws(()=>insertSql("feature_catalog",["code"])); });
test("target-seeded feature catalog fails closed for code-set or active-state drift", () => { const source=[{code:"analytics",display_name:"Analytics",description:null,sort_order:20,is_active:true,created_at:"2026-01-01T00:00:00Z"}]; const target=[{...source[0],is_active:false}]; assert.throws(()=>requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog(source,target,["code","display_name","description","sort_order","is_active","created_at"])),/ACTIVE_STATE/); assert.throws(()=>requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog(source,[],["code"])),/SOURCE_ONLY/); assert.throws(()=>requireTargetSeededFeatureCatalogParity(reconcileFeatureCatalog([],source,["code"])),/TARGET_ONLY/); });
test("target-seeded authorization catalogs require exact stable-key and semantic parity", () => { const source=[{role_code:"officer",permission_code:"view"},{role_code:"chief",permission_code:"manage"}], target=[{role_code:"chief",permission_code:"manage"},{role_code:"officer",permission_code:"view"}]; assert.doesNotThrow(()=>requireExactTargetSeededParity(reconcileExactTargetSeededRelation("role_permissions",source,target,["role_code","permission_code"]))); assert.throws(()=>requireExactTargetSeededParity(reconcileExactTargetSeededRelation("role_permissions",source,[{role_code:"officer",permission_code:"other"}],["role_code","permission_code"])),/STABLE_KEY/); assert.deepEqual(TARGET_SEEDED_REFERENCE_RELATIONS,["feature_catalog","roles","permissions","role_permissions"]); assert.ok(DATABASE_MODES.includes(TARGET_DATA_PREFLIGHT_MODE)); });
test("role-permission reconciliation identifies exact unmatched stable pairs without a merge rule", () => { const source=[{role_code:"chief",permission_code:"manage"},{role_code:"officer",permission_code:"view"},{role_code:"officer",permission_code:"audit"}], target=[{role_code:"chief",permission_code:"manage"},{role_code:"officer",permission_code:"view"}]; const result=reconcileRolePermissionDifferences(source,target); assert.equal(result.exactMatchCount,2); assert.deepEqual(result.sourceOnly,[{roleCode:"officer",permissionCode:"audit"}]); assert.deepEqual(result.targetOnly,[]); assert.equal(result.stableKeyParity,false); assert.ok(DATABASE_MODES.includes(ROLE_PERMISSIONS_RECONCILIATION_MODE)); assert.throws(()=>reconcileRolePermissionDifferences([{role_code:"officer",permission_code:"view"},{role_code:"officer",permission_code:"view"}],[]),/DUPLICATE/); });
test("the target-owned role-permission rule accepts only the five reviewed global defaults", () => { const target=[{role_code:"administrator",permission_code:"administer_department"}]; const source=[...target,{role_code:"administrator",permission_code:"manage_certifications"},{role_code:"administrator",permission_code:"manage_equipment"},{role_code:"supervisor",permission_code:"manage_certifications"},{role_code:"supervisor",permission_code:"manage_equipment"},{role_code:"supervisor",permission_code:"manage_training"}]; const reconciliation=requireTargetSeededRolePermissionRule(reconcileRolePermissionDifferences(source,target)); assert.equal(reconciliation.classification,"target-seeded reference data — excluded by design"); assert.throws(()=>requireTargetSeededRolePermissionRule(reconcileRolePermissionDifferences([...source,{role_code:"supervisor",permission_code:"manage_users"}],target)),/UNREVIEWED_SOURCE_ONLY/); assert.throws(()=>requireTargetSeededRolePermissionRule(reconcileRolePermissionDifferences(source,[...target,{role_code:"officer",permission_code:"submit"}])),/TARGET_ONLY/); });
test("schema-contract helpers emit aggregate-only source evidence and safe target classifications", () => { const rows=[{id:"a",legacy_note:null},{id:"b",legacy_note:"present"}]; assert.deepEqual(summarizeSourceColumn(rows,"legacy_note"),{sourceColumn:"legacy_note",rowCount:2,populatedRowCount:1,nullOrMissingRowCount:1,distinctValueCount:1,observedJsonTypeCounts:{string:1}}); assert.equal(classifyTargetOnlyColumn({column_name:"created_at",is_identity:false,column_default:"now()",is_nullable:"NO"}),"TARGET_DEFAULTED"); assert.equal(classifyTargetOnlyColumn({column_name:"required",is_identity:false,column_default:null,is_nullable:"NO"}),"REQUIRED_IMPORT_VALUE"); });
test("the approved firearm schema repair is exact and the source-only field cannot be dropped", () => { assert.deepEqual(FIREARM_ASSIGNMENTS_SCHEMA_REPAIR.statements,["ALTER TABLE public.firearm_assignments ADD COLUMN magazines_expected_return integer","ALTER TABLE public.firearm_assignments ADD CONSTRAINT firearm_assignments_magazines_expected_return_nonnegative CHECK (magazines_expected_return IS NULL OR magazines_expected_return >= 0) NOT VALID"]); assert.equal(classifySourceOnlyColumn("firearm_assignments","magazines_expected_return",{sourceColumn:"magazines_expected_return"}),"TARGET_SCHEMA_MISSING_COLUMN"); assert.ok(DATABASE_MODES.includes(SCHEMA_REPAIR_MODE)); assert.ok(DATABASE_MODES.includes(SCHEMA_SWEEP_MODE)); });
test("source equivalence check proves a mapping without emitting source values", () => { const result=compareSourceColumns([{legacy:2,current:2},{legacy:2,current:2},{legacy:null,current:null}],"legacy","current"); assert.deepEqual(result,{leftColumn:"legacy",rightColumn:"current",rowCount:3,equalRowCount:3,unequalRowCount:0,bothPopulatedRowCount:2,leftOnlyPopulatedRowCount:0,rightOnlyPopulatedRowCount:0,bothNullOrMissingRowCount:1}); });
test("source-target mappings allow only exact safe source columns and parameterized inserts", () => { const columns=[{column_name:"id",is_nullable:"NO",column_default:null,is_identity:false},{column_name:"name",is_nullable:"YES",column_default:null,is_identity:false}]; const mapping=validateColumnMapping("departments",[{id:"a",name:"dept"}],columns); assert.deepEqual(mapping.mapping,{id:"id",name:"name"}); assert.match(insertSql("departments",["id","name"]),/\$1::json/); assert.throws(()=>sourceColumns([{bad:"x", "unsafe-key":"no"}])); assert.throws(()=>quote("bad;drop")); });
test("foreign-key ordering is deterministic and cycles fail closed", () => { assert.deepEqual(topologicalImportOrder(["a","b","c"],[{child:"b",parent:"a"},{child:"c",parent:"b"}]),["a","b","c"]); assert.throws(()=>topologicalImportOrder(["a","b"],[{child:"a",parent:"b"},{child:"b",parent:"a"}]),/CYCLE/); });
const cycleRows = (overrides={}) => new Map([
  ["departments", [{id:"d1",department_id:"d1"}]],
  ["agency_training_attendees", [{id:"a1",department_id:"d1",certification_id:"c1",...overrides.attendee}]],
  ["training_certifications", [{id:"c1",department_id:"d1",source_training_attendee_id:"a1",...overrides.certification}]],
]);
const cycleRelations = ["departments","agency_training_attendees","training_certifications"];
const cycleForeignKeys = [
  {child:"agency_training_attendees",parent:"departments"}, {child:"training_certifications",parent:"departments"},
  {child:"agency_training_attendees",parent:"training_certifications"}, {child:"training_certifications",parent:"agency_training_attendees"},
];
test("two-phase nullable cycle preserves exact links while masking only phase-one values", () => {
  const plan=nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows());
  assert.deepEqual(plan.order,["departments",NULLABLE_TRAINING_CERTIFICATION_CYCLE.token]);
  assert.equal(plan.phaseOne.attendees[0].certification_id,null); assert.equal(plan.phaseOne.certifications[0].source_training_attendee_id,null);
  assert.equal(plan.restore.attendees[0].value,"c1"); assert.equal(plan.restore.certifications[0].value,"a1");
});
test("two-phase nullable cycle preserves source nulls without restoration", () => {
  const plan=nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({attendee:{certification_id:null},certification:{source_training_attendee_id:null}}));
  assert.equal(plan.restore.attendees[0].value,null); assert.equal(plan.restore.certifications[0].value,null);
});
test("two-phase nullable cycle fails closed for missing references and cross-tenant links", () => {
  assert.throws(()=>nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({attendee:{certification_id:"missing"}})),/CERTIFICATION_REFERENCE_MISSING/);
  assert.throws(()=>nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({certification:{department_id:"d2"}})),/CROSS_DEPARTMENT_CERTIFICATION_REFERENCE/);
});
test("two-phase nullable cycle fails closed for a missing attendee reference and any additional graph cycle", () => {
  assert.throws(()=>nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows({certification:{source_training_attendee_id:"missing"}})),/ATTENDEE_REFERENCE_MISSING/);
  assert.throws(()=>nullableTrainingCertificationCyclePlan([...cycleRelations,"other_a","other_b"],[...cycleForeignKeys,{child:"other_a",parent:"other_b"},{child:"other_b",parent:"other_a"}],cycleRows()),/TARGET_FOREIGN_KEY_CYCLE/);
});
test("two-phase nullable cycle rolls back if a second-phase restoration fails", async () => {
  const plan=nullableTrainingCertificationCyclePlan(cycleRelations,cycleForeignKeys,cycleRows()); const calls=[];
  await assert.rejects(()=>executeNullableTrainingCertificationCycle(plan,{begin:async()=>calls.push("begin"),insertAttendees:async()=>calls.push("insert-attendees"),insertCertifications:async()=>calls.push("insert-certifications"),restoreAttendees:async()=>calls.push("restore-attendees"),restoreCertifications:async()=>{calls.push("restore-certifications");throw Error("fail");},validate:async()=>calls.push("validate"),commit:async()=>calls.push("commit"),rollback:async()=>calls.push("rollback")}));
  assert.deepEqual(calls,["begin","insert-attendees","insert-certifications","restore-attendees","restore-certifications","rollback"]);
});
test("the object manifest is fixed, checksum complete, and tenant scoped", () => { assert.equal(OBJECT_MANIFEST.length,2); assert.match(objectManifestSha256,/^[0-9a-f]{64}$/); for(const object of OBJECT_MANIFEST){assert.ok(object.destinationKey.startsWith(`department-assets/${object.departmentId}/`)); assert.throws(()=>validateObjectBytes(object,new Uint8Array(0)),/SIZE/);} assert.notEqual(canonicalRowsHash([{a:1}]),canonicalRowsHash([{a:2}])); });
