import assert from "node:assert/strict"; import test from "node:test";
import { executeSyntheticTableMigration, planSyntheticTableMigration, validateSyntheticTableManifest } from "./synthetic-table-migration-core.mjs";
const departmentId="10000000-0000-4000-8000-000000000001";
const manifest={schemaVersion:1,synthetic:true,departmentId,tables:[{name:"departments",primaryKey:["id"],rows:[{id:departmentId,name:"Synthetic"}]},{name:"profiles",primaryKey:["id"],rows:[{id:"20000000-0000-4000-8000-000000000001",department_id:departmentId,email:"one@example.test"}]}]};
function adapter(){const rows=new Map(),checkpoints=new Set();return{rows,checkpoints,begin:async()=>{},commit:async()=>{},rollback:async()=>{},checkpointExists:async(t,c)=>checkpoints.has(`${t}:${c}`),recordCheckpoint:async(t,c)=>checkpoints.add(`${t}:${c}`),find:async(t,k)=>rows.get(`${t}:${JSON.stringify(k)}`),insert:async(t,row)=>rows.set(`${t}:${JSON.stringify({id:row.id})}`,row),reconcile:async()=>{}};}
test("dry-run planning is tenant bounded and deterministic",()=>{const a=planSyntheticTableMigration(manifest),b=planSyntheticTableMigration(manifest);assert.deepEqual(a,b);assert.equal(a.dryRun,true);assert.equal(a.totalRows,2);});
test("execution requires authorization and emits checkpoint plus rollback evidence",async()=>{const plan=planSyntheticTableMigration(manifest),db=adapter();await assert.rejects(executeSyntheticTableMigration(plan,db),/authorization/);const evidence=await executeSyntheticTableMigration(plan,db,{authorized:true});assert.equal(evidence.reconciled,true);assert.equal(evidence.rollback.length,2);});
test("cross-tenant and oversized manifests fail closed",()=>{assert.throws(()=>validateSyntheticTableManifest({...manifest,tables:[{...manifest.tables[1],rows:[{id:"20000000-0000-4000-8000-000000000001",department_id:"30000000-0000-4000-8000-000000000001"}]}]}),/Cross-tenant/);assert.throws(()=>validateSyntheticTableManifest({...manifest,tables:[{...manifest.tables[1],rows:Array(1001).fill(manifest.tables[1].rows[0])}]}),/bound/);});
test("conflicting destination rows are refused and rolled back",async()=>{const plan=planSyntheticTableMigration(manifest),db=adapter();db.find=async()=>({id:"different"});let rolled=false;db.rollback=async()=>{rolled=true};await assert.rejects(executeSyntheticTableMigration(plan,db,{authorized:true}),/Conflict refused/);assert.equal(rolled,true);});
